### PR TITLE
Initial Tests Implementation

### PR DESCRIPTION
**Pull request by amos-kibet**
- add initial test files
- clean up working tree
- fix: 🔧 change port number
- fix:🔧 edit file
- fix:🔧 remove dummy test file
- fix:🔧 add testTimeout settings
- fix(deps):🔧 add packages
- fix:🔧 remove dummy test file
- feat:💉 initial endpoints test
- fix:🔧 remove dummy test file
- fix:🔧 debug logger file implementation
- fix:🔧 debug logger file implementation
- fix(deps):🔧 add packages
- feat:⛳ create test data folder

### CODE REVIEW

**Review by kerenketepela — APPROVED** [review]
lgmt!

**Review by kerenketepela — APPROVED** [review]
lgmt!

**Comment by amos-kibet** [comment]
What is lgtm? 🎅

**Comment by sankaire** [comment]
legitimate

**Comment by amos-kibet** [comment]
Sawa

**Pull request merged**
